apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-cka-testing
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b

nodeGroups:
  - name: ng-1
    instanceType: m3.xlarge
    desiredCapacity: 3
    availabilityZones:
      - us-east-1a
      - us-east-1b