---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
  labels:
    name: test1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks-a
  labels:
    app: hello-eks-a
  namespace: test1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-eks-a
  template:
    metadata:
      labels:
        app: hello-eks-a
    spec:
      containers:
      - name: hello
        image: public.ecr.aws/aws-containers/hello-eks-anywhere:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-image-name
  labels:
    app: bad-image-name
  namespace: test1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bad-image-name
  template:
    metadata:
      labels:
        app: bad-image-name
    spec:
      containers:
      - name: hello
        image: bad-image-name-does-not-exist-k8s-pod-mon:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
  labels:
    name: test2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks-a
  labels:
    app: hello-eks-a
  namespace: test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-eks-a
  template:
    metadata:
      labels:
        app: hello-eks-a
    spec:
      containers:
      - name: hello
        image: public.ecr.aws/aws-containers/hello-eks-anywhere:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"